// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tedxdpnsuadpuqcwjptz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZHhkcG5zdWFkcHVxY3dqcHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTkwMzksImV4cCI6MjA2MjQ3NTAzOX0.phWh25hs6TFPKmy2YafBlvrRS6XTBhl8PSTzFQ8u_0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);